spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://dpg-cpe83mvsc6pc739b6ul0-a.singapore-postgres.render.com/kw_duo_db
    username: kw_duo_db_user
    password: 0ri4OXlX8S5UFqqkTdNgExmiIwqFgXQA
    driver-class-name: org.postgresql.Driver